# Generated by Django 4.1.5 on 2023-01-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
